os: linux
dist: jammy
language: java
python:
- '3.10'
jdk:
- openjdk21
cache:
  directories:
    - '$HOME/.cache/pip'
    - '$HOME/.sonar/cache'
branches:
  only:
  - main
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
- pip install -U pip
install:
- pip install -e '.[test]'
script:
- coverage run -m pytest --junitxml=results.xml
- coverage xml
- mypy --ignore-missing-imports src/ tests/
- flake8 src/ tests/
deploy:
  - provider: releases
    token:
      secure: dLjaEn+XqwH+/bbnXV2Oo7UZGh9aQCS1hOKNsQhMTYWEHfDQUzmAsgEKUnBBywP1G9WM7UCrqyvEE4AG5vt1++XP8w8VWgCyvk+lElGqCjzYVFSErIDdwN6v48nsskktzckQVlatEFl19JczWh4PSMi6zwn9Korn0E0V4wYQGkVrHxF6saFen7eF4RUK3gBOKL9sZrGWcVSfWSqjm6tcVZPDRH/Uo8U4clIVWICw8Sx6HBuGKdAX9DCDdAJ+T6cLPEN6oMx6yEpEyvvaDJrgqEmx6oJSBBJ7sMJyOOxxrs0VEPxKaztCE/nNK4oQAsKXCGC8jO1fcdSp7gE2oE79ejOaMLuWGLP9JibP7ebQaWnvQwXYO4ElPcQY9N0bIgwRrLI6lMTk/dxiiIRlMHZzHKs9wiw7lR+/yk/4POKyYJTvPhU3fVplD38GI8438CXBhG79+cl741A0umIiY8ta8MUv/bJucMYWf9WKtHJLwMlXrUxENjdgAL6qE3QPq6mCx941982lj07YqBF+aRVADC/bdmAHKbFT/GlywGpkPJFbWclRWq27Nyo58hzO/zStBZ58eLPBZD/Na7+yJDHmY7HjcxZ+UP0ZiB5iU7lwM0gd2EZ3rZSoHhdVfW72Vi2JprwUHgCZnugdRWnrRQU1DCweum0WdnKOdT+oYs3v+GM=
    file: "bogus.file"
    prerelease: true
    on:
      tags: true
    edge: true # opt in to dpl v2