import pandas as pd

from molgenis.capice_resources.core import Module, GlobalEnums
from molgenis.capice_resources.compare_model_features.ranker import Ranker
from molgenis.capice_resources.compare_model_features.orderer import Orderer
from molgenis.capice_resources.compare_model_features.normalizer import Normalizer
from molgenis.capice_resources.compare_model_features import CompareModelFeaturesEnum


class CompareModelFeatures(Module):
    def __init__(self):
        super().__init__(
            program='Compare model features',
            description='Generates an output file that can be used to compare 2 CAPICE models with '
                        'each other. Requires the CAPICE explain tool to be used on the models to '
                        'compare. The output from CAPICE explain can then be used as input for '
                        'this script to generate a comparison tsv file.'
                        'Please note that it is the user responsibility to keep track of was '
                        'supplied as "explain_1" and "explain_2".'

        )

    @staticmethod
    def _create_module_specific_arguments(parser):
        required = parser.add_argument_group('Required arguments')
        optional = parser.add_argument_group('Optional arguments')

        required.add_argument(
            '-a',
            '--explain-1',
            type=str,
            required=True,
            help='Location of the file generated by the capice explain tool for the first model'
                 'supplied as a (gzipped) tsv file. Should contain the following columns:'
                 'feature, gain, total_gain, weight, cover & total_cover'
        )
        required.add_argument(
            '-b',
            '--explain-2',
            type=str,
            required=True,
            help='Location of the file generated by the capice explain tool for the second model'
                 'supplied as a (gzipped) tsv file. Should contain the following columns:'
                 'feature, gain, total_gain, weight, cover & total_cover'
        )

        required.add_argument(
            '-o',
            '--output',
            type=str,
            required=True,
            help='Path to generate the output file to. Will generate directories if they do not'
                 'exist yet. Must be a (gzipped) tsv file.'
        )

        optional.add_argument(
            '-f',
            '--force',
            action='store_true',
            help='Force overwrite the output file if it already exists.'
        )

        return parser

    def _validate_module_specific_arguments(self, parser):
        explain_1 = self.input_validator.validate_icli_file(
            parser.get_argument('explain_1'),
            GlobalEnums.TSV_EXTENSIONS.value
        )
        explain_2 = self.input_validator.validate_icli_file(
            parser.get_argument('explain_2'),
            GlobalEnums.TSV_EXTENSIONS.value
        )
        output = self.input_validator.validate_ocli_directory(
            parser.get_argument('output'),
            GlobalEnums.TSV_EXTENSIONS.value,
            parser.get_argument('force')
        )
        return {
            **explain_1,
            **explain_2,
            **output
        }

    def run_module(self, arguments):
        explain_1 = self._read_pandas_tsv(arguments['explain_1'], CompareModelFeaturesEnum.list())
        self._process_explain(explain_1)
        explain_2 = self._read_pandas_tsv(arguments['explain_2'], CompareModelFeaturesEnum.list())
        self._process_explain(explain_2)
        merge = self._merge_explains(explain_1, explain_2)
        orderer = Orderer()
        out = orderer.order(merge)
        return {'dataframe': out, GlobalEnums.OUTPUT.value: arguments['output']}

    def _process_explain(self, explain: pd.DataFrame) -> None:
        normalizer = Normalizer()
        before_normalized_columns = explain.columns
        normalizer.normalize_column(explain, CompareModelFeaturesEnum.GAIN.value)
        # new_columns should now have the normalized column, regardless if GAIN or other
        new_columns = self._obtain_new_column(explain.columns, before_normalized_columns)
        ranker = Ranker()
        ranker.add_rank(explain, new_columns)

    @staticmethod
    def _merge_explains(explain1: pd.DataFrame, explain2: pd.DataFrame) -> pd.DataFrame:
        return pd.merge(
            explain1,
            explain2,
            how='outer',
            on=CompareModelFeaturesEnum.FEATURE.value,
            suffixes=('_model1', '_model2')
        )

    @staticmethod
    def _obtain_new_column(columns1: pd.DataFrame.columns, columns2: pd.DataFrame.columns) -> \
            list[str]:
        """
        Function to check if a column exists in columns1 but not in columns2

        Args:
            columns1:
                pandas.DataFrame.columns object of the first dataframe. Checks if a column does
                not exist in columns2.
            columns2:
                pandas.DataFrame.columns object of the second dataframe. Is a reference for column1.

        Returns:
            list:
                List of all the columns that do exist in columns1 but not in columns2.
        """
        missing = []
        for column in columns1:
            if column not in columns2:
                missing.append(column)
        return missing

    def export(self, output):
        self.exporter.export_pandas_file(output[GlobalEnums.OUTPUT.value], output['dataframe'])


def main():
    CompareModelFeatures().run()


if __name__ == '__main__':
    main()
